package sk.upjs.paz1c.nezabudal.forms;

import java.time.zone.ZoneRulesProvider;
import sk.upjs.paz1c.nezabudal.dao.ObjectFactory;
import sk.upjs.paz1c.nezabudal.entity.Category;
import sk.upjs.paz1c.nezabudal.gui.models.CategoryComboBoxModel;
import sk.upjs.paz1c.nezabudal.gui.models.ItemTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Mikey
 */
public class RemembrallForm extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public RemembrallForm() {
        initComponents();
        // toto checkbox ked je sam
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jProgressBar1 = new javax.swing.JProgressBar();
        addCategoryButton = new javax.swing.JButton();
        removeCategoryButton = new javax.swing.JButton();
        addItemButton = new javax.swing.JButton();
        removeLoanButton = new javax.swing.JButton();
        lentCheckBox = new javax.swing.JCheckBox();
        ownedCheckBox = new javax.swing.JCheckBox();
        loanLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        removeItemButton = new javax.swing.JButton();
        addLoanButton = new javax.swing.JButton();
        notBorrowedCheckBox = new javax.swing.JCheckBox();
        categoryComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemTable = new javax.swing.JTable();
        editCategoryButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Remembrall");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 51, 51));

        addCategoryButton.setText("Pridaj kategóriu");
        addCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCategoryButtonActionPerformed(evt);
            }
        });

        removeCategoryButton.setText("Odstráň kategóriu");
        removeCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCategoryButtonActionPerformed(evt);
            }
        });

        addItemButton.setText("Pridaj predmet");
        addItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemButtonActionPerformed(evt);
            }
        });

        removeLoanButton.setText("Odstráň pôžičku");
        removeLoanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeLoanButtonActionPerformed(evt);
            }
        });

        lentCheckBox.setText("Požičal som");
        lentCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lentCheckBoxMousePressed(evt);
            }
        });
        lentCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lentCheckBoxActionPerformed1(evt);
                lentCheckBoxActionPerformed(evt);
            }
        });

        ownedCheckBox.setSelected(true);
        ownedCheckBox.setText("Požičali mi");
        ownedCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ownedCheckBoxMousePressed(evt);
            }
        });
        ownedCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownedCheckBoxActionPerformed(evt);
            }
        });

        loanLabel.setText("Pôžička");

        categoryLabel.setText("Kategória");

        removeItemButton.setText("Odstráň predmet");
        removeItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeItemButtonActionPerformed(evt);
            }
        });

        addLoanButton.setText("Pridaj pôžičku");
        addLoanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLoanButtonActionPerformed(evt);
            }
        });

        notBorrowedCheckBox.setText("Nepožičané");
        notBorrowedCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notBorrowedCheckBoxActionPerformed(evt);
            }
        });

        categoryComboBox.setModel(ObjectFactory.INSTANCE.getCategoryComboBoxModel());
        categoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryComboBoxActionPerformed(evt);
            }
        });

        itemTable.setModel(new ItemTableModel(getSelectedCategory()));
        jScrollPane1.setViewportView(itemTable);

        editCategoryButton.setText("Uprav kategóriu");
        editCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCategoryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(categoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loanLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lentCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ownedCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(notBorrowedCheckBox)
                                .addGap(190, 375, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(removeCategoryButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editCategoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addItemButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addLoanButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removeLoanButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removeItemButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCategoryButton)
                    .addComponent(removeCategoryButton)
                    .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editCategoryButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ownedCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lentCheckBox)
                    .addComponent(notBorrowedCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addItemButton)
                        .addGap(11, 11, 11)
                        .addComponent(removeItemButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addLoanButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeLoanButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lentCheckBoxActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lentCheckBoxActionPerformed1

    }//GEN-LAST:event_lentCheckBoxActionPerformed1

    private void lentCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lentCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lentCheckBoxActionPerformed

    private void lentCheckBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lentCheckBoxMousePressed
        if (ownedCheckBox.isSelected()) {
            ownedCheckBox.doClick();
        } else if (notBorrowedCheckBox.isSelected()) {
            notBorrowedCheckBox.doClick();
        }
    }//GEN-LAST:event_lentCheckBoxMousePressed

    private void ownedCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownedCheckBoxActionPerformed

    }//GEN-LAST:event_ownedCheckBoxActionPerformed

    private void ownedCheckBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ownedCheckBoxMousePressed
        if (lentCheckBox.isSelected()) {
            lentCheckBox.doClick();
        } else if (notBorrowedCheckBox.isSelected()) {
            notBorrowedCheckBox.doClick();
        }
    }//GEN-LAST:event_ownedCheckBoxMousePressed

    private void addCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCategoryButtonActionPerformed
        AddCategoryDialog kategoriaForm = new AddCategoryDialog(this, true);
        kategoriaForm.setVisible(true);

        //----
        // ( (KategoriaComboBoxModel) kategoriaComboBox.getModel() ).refresh();
    }//GEN-LAST:event_addCategoryButtonActionPerformed

    private void notBorrowedCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notBorrowedCheckBoxActionPerformed
        if (lentCheckBox.isSelected()) {
            lentCheckBox.doClick();
        } else if (ownedCheckBox.isSelected()) {
            ownedCheckBox.doClick();
        } 
    }//GEN-LAST:event_notBorrowedCheckBoxActionPerformed

    private void categoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryComboBoxActionPerformed
        // AttributeValuesTableModel model = (AttributeValuesTableModel ) attributesTable.getModel();
        // model.aktualizovat(getSelectedCategory());

        // attributesTable.setModel(new AttributeValuesTableModel(getSelectedCategory()));
        
        ((ItemTableModel) itemTable.getModel()).refresh(getSelectedCategory());
    
    }//GEN-LAST:event_categoryComboBoxActionPerformed

    private void removeCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCategoryButtonActionPerformed
        CategoryRemoveDialog categoryRemoveDialog = new CategoryRemoveDialog(this, true);
        categoryRemoveDialog.setVisible(true);
    }//GEN-LAST:event_removeCategoryButtonActionPerformed

    private void removeLoanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeLoanButtonActionPerformed
        LoanRemoveDialog loanRemoveDialog = new LoanRemoveDialog(this, true);
        loanRemoveDialog.setVisible(true);
    }//GEN-LAST:event_removeLoanButtonActionPerformed

    private void addLoanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLoanButtonActionPerformed
        AddLoanDialog itemDialog = new AddLoanDialog(this, true);

        // refresh model
        itemDialog.setVisible(true);
    }//GEN-LAST:event_addLoanButtonActionPerformed

    private void removeItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeItemButtonActionPerformed
        ItemRemoveDialog itemRemoveDialog = new ItemRemoveDialog(this, true);
        itemRemoveDialog.setVisible(true);
    }//GEN-LAST:event_removeItemButtonActionPerformed

    private void addItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemButtonActionPerformed
        AddItemDialog loanDialog = new AddItemDialog(this, true);
        loanDialog.setVisible(true);
    }//GEN-LAST:event_addItemButtonActionPerformed

    private void editCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCategoryButtonActionPerformed
        AddCategoryDialog kategoriaForm = new AddCategoryDialog(this, true, getSelectedCategory());
        kategoriaForm.setVisible(true);
    }//GEN-LAST:event_editCategoryButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemembrallForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemembrallForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemembrallForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemembrallForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemembrallForm().setVisible(true);
            }
        });
    }

      private Category getSelectedCategory() {
        return (Category) ((CategoryComboBoxModel) categoryComboBox.getModel()).getSelectedItem();
    }
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCategoryButton;
    private javax.swing.JButton addItemButton;
    private javax.swing.JButton addLoanButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<Category> categoryComboBox;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JButton editCategoryButton;
    private javax.swing.JTable itemTable;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox lentCheckBox;
    private javax.swing.JLabel loanLabel;
    private javax.swing.JCheckBox notBorrowedCheckBox;
    private javax.swing.JCheckBox ownedCheckBox;
    private javax.swing.JButton removeCategoryButton;
    private javax.swing.JButton removeItemButton;
    private javax.swing.JButton removeLoanButton;
    // End of variables declaration//GEN-END:variables
}
